### ISSUE TITLE
`auto` declaration of (ordinary) function params is not legal in c++14

### ISSUE THREAD

**Issue by evaleev** [jakobandersen/graph_canon#2]
https://github.com/jakobandersen/graph_canon/blob/1f63d239a2a5cd79ee58ea220a632ef3411be8b3/include/graph_canon/aut/pruner_schreier.hpp#L316

does not compile with clang ... it's probably a gcc-only extension.

**Comment by jakobandersen** [comment]
Fixed in v0.4.
